### ISSUE TITLE
Use after_setup_theme action

### ISSUE THREAD

**Issue by mattradford** [10degrees/10degrees-base#19]
https://github.com/10degrees/10degrees-base/blob/90d0f567dd3cf87dea21f2841c66b93dee47face/functions.php#L45

Ever get that weirdness when some actions or filters don't work?

`functions.php` should use `after_setup_theme` rather than `init`.

See https://codex.wordpress.org/Plugin_API/Action_Reference

**Comment by BenRutlandWeb** [comment]
New theme structure removes the `after_setup_theme` action completely so there is more control for each component as to where it is loaded.
