### ISSUE TITLE
Change Spacer Block

### ISSUE THREAD

**Issue by AliceKLWilliams** [10degrees/10degrees-base#33]
The spacer block currently allows users to enter their own pixel spacings for desktop/tablet/mobile. This can be confusing to users, especially those with not a lot of Gutenberg experience.

Replace the spacer block with 3 new blocks: Small Spacer, Medium Spacer and Large Spacer. Predefine the heights of all these, ensuring to also provide heights for mobile/tablet.

It would also be useful to put these blocks into their own "Spacer" block category, so that they are easy to find.

**Comment by BenRutlandWeb** [comment]
I think having one spacer but instead of having a number input, have a dropdown with sm/md/lg. these can set a custom property that can then be customized per project.

**Comment by AliceKLWilliams** [comment]
Yep, I agree. That'll also reduce the amount of files we need and the amount of clutter in the block directory.

**Comment by AliceKLWilliams** [comment]
Fixed by https://github.com/10degrees/10degrees-base/commit/a6874adc4bbc4abcbb8ac043afad73c7a031c0e4
