### ISSUE TITLE
Custom Taxonomies not appearing in Gutenberg sidebar

### ISSUE THREAD

**Issue by AliceKLWilliams** [10degrees/10degrees-base#65]
The stub the `make:cpt` command uses needs to set `'show_in_rest' => true` when registering custom taxonomies. Else they won't appear in the Gutenberg sidebar.

**Comment by mattradford** [comment]
Can't repoduce. `make:cpt` sets `'show_in_rest' => true`

**Comment by mattradford** [comment]
@BenRutlandWeb @AliceKLWilliams Please test this next time your create a CPT.

**Comment by AliceKLWilliams** [comment]
'show_in_rest' => true needs to be added to the taxonomy registration, not the CPT registration
